spring.flyway.enabled: false

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ia_timed_event_service
    username: sa
    password:
    platform: h2
  quartz:
    jdbc:
      initialize-schema: embedded
    properties:
      org:
        quartz:
          jobStore:
            tablePrefix: QRTZ_

ccdGatewayUrl: ${CCD_GW_URL:http://localhost:3453}
document_management.url: ${DM_URL:http://127.0.0.1:4506}

